### ISSUE TITLE
Doesn't work in Node 8

### ISSUE THREAD

**Issue by SamClayton** [campbellwmorgan/docker-wait#1]
Looks like deprecated fs API usage.

```
Step 21/23 : RUN docker-wait docker/docker-wait.json
 ---> Running in 46b9d3a4e9f4
/usr/lib/node_modules/docker-wait/lib/main.coffee:56
    contents = fs.readfileSync(configPath);
                  ^

TypeError: fs.readfileSync is not a function
    at Object.<anonymous> (/usr/lib/node_modules/docker-wait/lib/main.coffee:58:17)
    at Object.<anonymous> (/usr/lib/node_modules/docker-wait/lib/main.coffee:1:1)
    at Module._compile (module.js:573:30)
    at Object.loadFile (/usr/lib/node_modules/docker-wait/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/lib/node_modules/docker-wait/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by campbellwmorgan** [comment]
Hi @SamClayton thanks for giving the library a try. I hadn't imagined that it had any uptake at all.
I'm no longer using this anymore in production (I tend to prefer other solutions such as trying to "frontload" as many processes as possible in the docker build steps so that startup time is less than a second or use a health check to establish that a service is up), but I would gladly transfer this to you / add you as a contributor if it is important to your current setup.

I would also add that from the quoted text, you seem to be running this inside a docker build. No doubt you have some really good reasons for doing it, but if you haven't already heard about it, I would look into [docker-compose ](https://docs.docker.com/compose/) which has taken all the pain out of coordinating multiple docker services for me.
